<!DOCTYPE html>
<html lang="en">
<head>
    <title>Smart bots</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon">
    <link rel="stylesheet" href="css/bootstrap/bootstrap.min.css">

    <style>
        .card {
            height: 200px;
        }
        .py-8 {
            padding-top: 8em;
            padding-bottom: 8em;
        }
    </style>
</head>

<body>
<div class="container-fluid py-8">
    <div class="d-flex justify-content-center fixed-top pt-5">
        <h2 class="font-weight-light">Smart telegram bots</h2>
    </div>
    <div class="row flex-row flex-nowrap">
        <div class="col-xl-3 col-lg-4 col-md-5 col-sm-7 col-xs-12">
            <div class="card text-dark bg-light">
                <div class="card-body">
                    <a href="https://t.me/SmartVideoConverterBot">
                        <h5 class="card-title">@SmartVideoConverterBot</h5>
                    </a>
                    <ul>
                        <li>Convert video to other formats</li>
                        <li>Compress video</li>
                        <li>Change video resolution</li>
                        <li>Extract audio from video</li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-xl-3 col-lg-4 col-md-5 col-sm-7 col-xs-12">
            <div class="card text-dark bg-light">
                <div class="card-body">
                    <a href="https://t.me/SmartConverter_bot">
                        <h5 class="card-title">@SmartConverter_bot</h5>
                    </a>
                    <ul>
                        <li>Convert document, link, image, sticker, text to other formats</li>
                        <li>Merge pdf files</li>
                        <li>Create sticker from image</li>
                        <li>Merge images into pdf</li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-xl-3 col-lg-4 col-md-5 col-sm-7 col-xs-12">
            <div class="card text-dark bg-light">
                <div class="card-body">
                    <a href="https://t.me/SmartAudioConverterBot">
                        <h5 class="card-title">@SmartAudioConverterBot</h5>
                    </a>
                    <ul>
                        <li>Convert audio to other formats</li>
                        <li>Compress audio</li>
                        <li>Change audio bitrate</li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-xl-3 col-lg-4 col-md-5 col-sm-7 col-xs-12">
            <div class="card text-dark bg-light">
                <div class="card-body">
                    <a href="https://t.me/SmartFileUtilsBot">
                        <h5 class="card-title">@SmartFileUtilsBot</h5>
                    </a>
                    <ul>
                        <li>Convert audio to other formats</li>
                        <li>Compress audio</li>
                        <li>Change audio bitrate</li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-xl-3 col-lg-4 col-md-5 col-sm-7 col-xs-12">
            <div class="card text-dark bg-light">
                <div class="card-body">
                    <a href="https://t.me/SmartUnzipperBot">
                        <h5 class="card-title">@SmartUnzipperBot</h5>
                    </a>
                    <ul>
                        <li>Extract files from archive</li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-xl-3 col-lg-4 col-md-5 col-sm-7 col-xs-12">
            <div class="card text-dark bg-light">
                <div class="card-body">
                    <a href="https://t.me/SmartRenamerBot">
                        <h5 class="card-title">@SmartRenamerBot</h5>
                    </a>
                    <ul>
                        <li>Rename telegram files</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>