<!DOCTYPE html>
<html lang="en">
<head>
    <title>Smart bots</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon">
    <link rel="stylesheet" href="css/bootstrap/bootstrap.min.css">

    <style>
        .card {
            height: 200px;
        }

        .py-10 {
            padding-top: 10em;
        }
    </style>
</head>

<body>
<div class="container-fluid py-10">
    <div class="fixed-top pt-5">
        <h2 class="d-flex justify-content-center font-weight-light">Smart telegram bots</h2>
        <h2 class="d-flex justify-content-center font-weight-light">(daily ~1500 active users)</h2>
    </div>
    <div class="row flex-row flex-nowrap">
        <div class="col-xl-3 col-lg-4 col-md-5 col-sm-7 col-xs-12">
            <div class="card text-dark bg-light">
                <div class="card-body">
                    <a href="https://t.me/SmartPaymentBot">
                        <h5 class="card-title text-center">@SmartPaymentBot</h5>
                    </a>
                    <ul class="mt-4">
                        <li>The bot for buying a subscription to the bots
                            <ul>
                                <li><b>1 month - $1</b></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-xl-3 col-lg-4 col-md-5 col-sm-7 col-xs-12">
            <div class="card text-dark bg-light">
                <div class="card-body">
                    <a href="https://t.me/SmartVideoConverterBot">
                        <h5 class="card-title text-center">@SmartVideoConverterBot</h5>
                    </a>
                    <ul class="mt-4">
                        <li>Convert video to other formats</li>
                        <li>Compress video</li>
                        <li>Change video resolution</li>
                        <li>Extract audio from video</li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-xl-3 col-lg-4 col-md-5 col-sm-7 col-xs-12">
            <div class="card text-dark bg-light">
                <div class="card-body">
                    <a href="https://t.me/SmartConverter_bot">
                        <h5 class="card-title text-center">@SmartConverter_bot</h5>
                    </a>
                    <ul class="mt-4">
                        <li>Convert document, link, image, sticker, text to other formats</li>
                        <li>Merge pdf files</li>
                        <li>Create sticker from image</li>
                        <li>Merge images into pdf</li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-xl-3 col-lg-4 col-md-5 col-sm-7 col-xs-12">
            <div class="card text-dark bg-light">
                <div class="card-body">
                    <a href="https://t.me/SmartAudioConverterBot">
                        <h5 class="card-title text-center">@SmartAudioConverterBot</h5>
                    </a>
                    <ul class="mt-4">
                        <li>Convert audio to other formats</li>
                        <li>Compress audio</li>
                        <li>Change audio bitrate</li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-xl-3 col-lg-4 col-md-5 col-sm-7 col-xs-12">
            <div class="card text-dark bg-light">
                <div class="card-body">
                    <a href="https://t.me/SmartFileUtilsBot">
                        <h5 class="card-title text-center">@SmartFileUtilsBot</h5>
                    </a>
                    <ul class="mt-4">
                        <li>Extract text from an image</li>
                        <li>Create an archive</li>
                        <li>Image editor</li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-xl-3 col-lg-4 col-md-5 col-sm-7 col-xs-12">
            <div class="card text-dark bg-light">
                <div class="card-body">
                    <a href="https://t.me/SmartUnzipperBot">
                        <h5 class="card-title text-center">@SmartUnzipperBot</h5>
                    </a>
                    <ul class="mt-4">
                        <li>Extract files from archive</li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-xl-3 col-lg-4 col-md-5 col-sm-7 col-xs-12">
            <div class="card text-dark bg-light">
                <div class="card-body">
                    <a href="https://t.me/SmartRenamerBot">
                        <h5 class="card-title text-center">@SmartRenamerBot</h5>
                    </a>
                    <ul class="mt-4">
                        <li>Rename telegram files</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>